### PR TITLE
One line change to openblas-feedstock/recipe/build.sh to expose "sbgemm" entry point on POWER

### PR DESCRIPTION
**Pull request by austinpagan**
Checklist
* [ X] Used a fork of the feedstock to propose changes
* [ X] Bumped the build number (if the version is unchanged)
* [ n/a] Reset the build number to `0` (if the version changed)
* [ n/a] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (`@conda-forge-admin, please rerender`)
* [ X] Ensured the license file is being packaged.

closes https://github.com/ContinuumIO/anaconda-issues/issues/12355

### CODE REVIEW

**Comment by austinpagan** [comment]
@chenghlee I am not sure, but are there any action items for me on this?

**Comment by austinpagan** [comment]
@chenghlee I am not sure, but are there any action items for me on this?

**Comment by austinpagan** [comment]
Is there more I can do here? If this is going to be open for a while, but there's no more action items for me, that would be good to know...

**Comment by chenghlee** [comment]
@austinpagan There's nothing more you need to do; we will merge this into the recipe when Anaconda next updates its OpenBLAS packages.

**Comment by ScottBailey** [comment]
@chenghlee What's the status here?

**Comment by cbouss** [comment]
Closing as BUILD_BFLOAT16 is set appropriately by OpenBLAS makefile.

**Pull request closed without merging**
