### PR TITLE
Set SONAME for osx

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (`@conda-forge-admin, please rerender`)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @soapy1

**Comment by isuruf** [comment]
ping

**Comment by isuruf** [comment]
ping again

**Comment by isuruf** [comment]
@kalefranz, @mingwandroid, @msarahan, @jjhelmus  can one of you please merge this? I'm trying to make defaults and conda-forge compatible and this has been sitting here for more than a month.

**Comment by isuruf** [comment]
Thanks. I've also sent this upstream and the next release should have a install_name without the full version in it.

**Comment by jjhelmus** [comment]
Sorry for overlooking this @isuruf.  I'll get this built.  I want to get the [SkyLake-X patch]( (https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/gh2111.patch) merged as well as this has been causing some issues with NumPy and Numba.

**Pull request merged**
